

export type Patient = {
  id: string;
  name: string;
  age: number;
  birthDate: string;
  cpf: string;
  phone: string;
  email: string;
  emailVerified: boolean;
  verificationToken?: string | null;
  tokenExpiry?: Date | null;
  city: string;
  state: string;
  lastVisit: string;
  // This top-level status can represent if the patient has any pending exams.
  status: 'Requer Validação' | 'Validado'; 
  priority?: 'Urgente' | 'Alta' | 'Normal';
  avatar: string;
  avatarHint: string;
  gender: string;
  conversationHistory: string;
  reportedSymptoms: string;
  examResults: string; // Summary of all results for AI context
  doctorNotes?: string; // Kept for general notes, but validation is per exam.
  preventiveAlerts?: string[];
  healthGoals?: {
      title: string;
      description: string;
      progress: number;
  }[];
  // Final explanation at patient level is being deprecated in favor of per-exam.
  finalExplanation?: string;
  finalExplanationAudioUri?: string;
  // Wellness plan generated by AI Nutritionist based on all exam results
  wellnessPlan?: {
    dietaryPlan: string;
    exercisePlan: string;
    mentalWellnessPlan: string;
    dailyReminders: Array<{
      icon: 'Droplet' | 'Clock' | 'Coffee' | 'Bed' | 'Dumbbell';
      title: string;
      description: string;
    }>;
    weeklyTasks: Array<{
      id: string;
      category: 'nutrition' | 'exercise' | 'mental' | 'general';
      title: string;
      description: string;
      dayOfWeek?: string;
      completed: boolean;
      completedAt?: string;
    }>;
    lastUpdated: string;
  };
};

// Type for authentication that includes the hashed password
export type PatientWithPassword = Patient & { password?: string | null };

export type Doctor = {
  id: string;
  name: string;
  crm: string;
  specialty: string;
  city: string;
  state: string;
  online: boolean;
  avatar: string;
  avatarHint: string;
  email: string;
  emailVerified: boolean;
  verificationToken?: string | null;
  tokenExpiry?: Date | null;
  level: number;
  xp: number;
  xpToNextLevel: number;
  validations: number;
  badges: {
      name: string;
      icon: 'Award' | 'Star' | 'Clock' | 'Zap' | 'CheckSquare';
      description: string;
  }[];
  // NOVO CAMPO: Disponibilidade do médico
  availability?: { date: string; time: string; available: boolean }[];
};

// Type for authentication that includes the hashed password
export type DoctorWithPassword = Doctor & { password?: string | null };

export type Admin = {
  id: string;
  name: string;
  email: string;
  avatar: string;
  role: string;
};

export type AdminWithPassword = Admin & { password?: string | null };

export type Exam = {
  id: string;
  patientId: string;
  type: string;
  date: string;
  result: string; // A summary of the result, e.g., the preliminary diagnosis
  icon: string; // Lucide icon name
  preliminaryDiagnosis: string;
  explanation: string;
  suggestions: string;
  results?: { name: string; value: string; reference: string }[];
  specialistFindings?: Array<{
    specialist: string;
    findings: string;
    clinicalAssessment: string;
    recommendations: string;
  }>;
  status: 'Requer Validação' | 'Validado';
  doctorNotes?: string;
  finalExplanation?: string;
  finalExplanationAudioUri?: string;
};

export type Appointment = {
    id: string;
    patientId: string;
    patientName: string;
    patientAvatar?: string;
    doctorId: string;
    date: string;
    time: string;
    type: string;
    status: 'Agendada' | 'Concluída' | 'Cancelada';
};

export type CallRecording = {
    transcription: string;
    summary: string;
    processedAt: string;
    audioStoredAt: string | null;
};

export type Consultation = {
    id: string;
    doctorId: string;
    patientId: string;
    roomId: string;
    transcription: string;
    summary: string;
    date: string;
    type: 'video-call' | 'chat';
};

export type AdminSettings = {
    id: string;
    platformName: string;
    platformDescription: string;
    supportEmail: string;
    maxFileSize: number; // MB
    sessionTimeout: number; // dias
    notifyNewPatient: boolean;
    notifyNewDoctor: boolean;
    notifyNewExam: boolean;
    notifyNewConsultation: boolean;
    notifySystemAlerts: boolean;
    notifyWeeklyReport: boolean;
    createdAt: Date;
    updatedAt: Date;
};

export type AuditLog = {
    id: string;
    adminId: string;
    adminName: string;
    adminEmail: string;
    action: string; // 'update_settings', 'change_password', 'create_admin', etc
    entityType: string; // 'admin_settings', 'admin_auth', 'admin', etc
    entityId?: string | null; // ID do registro afetado, se aplicável
    changes?: Array<{
        field: string;
        oldValue: string | number | boolean | null;
        newValue: string | number | boolean | null;
    }>;
    metadata?: Record<string, any>;
    ipAddress?: string | null;
    userAgent?: string | null;
    createdAt: Date;
};
